dist: trusty

language: java

jdk:
  - oraclejdk8

notifications:
      slack: gojava5:NHIHdfuSA5H2riwEG9X8dL8V
      email: false

addons:
    sonarqube:
      token:
        secure: hbTvoCnFEF2kwBGbGOtUHVEI90A985IDH1lrF/Uwy9YPR9vl1XwmC/NNkkVXgqHXdm2IuHjFOqkkQH5TcVcus880KPX3T7OtvzJaTDKbQzxttx904wB2fBcJcbGuqGc1WN9+wxwXIRLXecgISYFWfkI4Po6FrWwT0aY1wrBGgDzGRwNedvV+NT4bSo2AAg8BCgHgfZpWAdC7Wdf9L7HqEhTRM30fGD+Ry5LKvumNmhMvTKIiHKanj84sv7joxC8zvItqjx7bdulc7DRxChxSt0t4w3Iy3k9zxyOaGcyWxnTHxBqKNZJgzTnmLxnc9VSwLZkwf0t3tm88tl37te5R5T8NPPBO4pGo41Qz5/nvmZF3nvQdEqzr4LXeRNyClDTurf7t1o9/bJYgfCUIxToufIE8RdAeOoMdYtsj5DgBs6HZ5XKkLlXhkdmtfPsHtXXO1h6uZr/AliD0xuH561mPZ5ZeVwktlNUXqi+nzBOvwSeTUh9o+44s9Rug0UGaRqZ5YGaEQgIjTmyqnRFHzLqkohg2X6hNQVnm2YoAP4OCg9bXLkySY6RcWF0t9/ak+b0AvHAh2YJLOpN7McCCa6/tzbLKeidyuPw3Yrpyz2Nay4q5zQoyi0h+zKa1ZigiVOaisgTIjdf3vEHBBHDAu/AyhNrjCTqDWcoBA3F7eDXyiWs=
      github_token:
        secure: XK1vB/wRnY2138Y+okqnptH53NUK4ucnF1iNo3v3u4flp4rkHNurDbz25pSsFU4/0TDqsWZgM9VDxRzF4cvMN1AivvmRu/xlYpgqbR9Tm7uMmD6xssciyL7jmLc04N7Npa8mLmXre3+vQ0dcXARiZ+3GqfuiB0na4qAnU72719wCuE99W/w64JecSM7pyvVSsghFigC5TreBdZrNJO9C36g1brGXh9GwFXEtwIvgb2dGEKZNxPvDOGJKIRrJtY9yCLXp63IPTWWOVNWnKNZvgf1zS+uanBzNztU+z5CpGPs/43w+6dfQeGYv7FskMj8ng7V1TsPGHfn0e7sSDVmcXLY3sEKR53r0NSEUsexmTSmGKW0Eh1t9k0UaXElQTNKBqzwginlloePfkWLLJxngcAQ9jiUwi/FqCdmGfygrb8PdPBPAU5tC4j9lE1eA2/yAkmaOXl7b1OY3NHGhm5iphnTNWYgikH3e4F0pwzx3bBB/1lNUptryrlvZ6Y8yM77izeVKHinSEx1dzI7TX7hbiqv/OgZGzfJWb5CRlTE3hbtEexfuoXCXMj+3s66GPQHq5oGDhoWtRcXW8hVdI6Nj4ANBFQLXfQFIp6aphw7ATvCHTnFA16dlNaz6CxOe/iS8n7x0uufONn0IcDIwc05dH/vMpmG7NZEwHZeFljnchSY=

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar

script:
    - mvn clean test jacoco:report coveralls:report
    - sonar-scanner

