dist: trusty

language: java

jdk:
  - oraclejdk8

notifications:
      slack: gojava5:NHIHdfuSA5H2riwEG9X8dL8V
      email: false

addons:
    sonarqube:
      token:
        secure: gS8cZNVZVhURxw/r/GXacfVcbH6Fq4HxxEH+M4lNhNuliPaHrgw/0YCQ6+KacGXdD0LpZkB/5M/DdvMQxmt6JB97OOpkL2J0voUVP2OCN6c3juwoK/3JnV0zudrXbV/X/2uGiWIs3rTsfTPP/8ZtjDe29Pmt48SQ0zUpYhFPg9J55wSCaE5hymLwunS2mV4e4lf8tj6LI7ayKVVjecWyl27G5m8b7iXjU6CaEbOGwkaQKxvkJsz/564t8Y8O2W/Hw8hzSv5MCbWf4fVgCwqfcUKmAHYFd5/BJb0i5XrA9s8scBIzW5yRl+Rqz841MjfLfdpz4HjnWkzCPqeM8eeU2qDsJ5UD9ZxrI51wyACxUNtiHjJZmowGG/+SV/7DPIIQxYwAhtWFx4+mAiLLo18UYTnCFYkhOcsJdpcYJtsB6OLVHTbQqc5R3lH/mpvdqCIVqndLAAQomwe6GGCGryvVqlzq6rgKTGj03eUCqmW7/C1jStXKDYKCijy+wMDNcBlBLMERUrx53rzsvWkv9ynzhQGlKURVyRMGDyFFznDQEJ9hzfGSGCBB2a64yBhmrSkJqzRPxGrNKHP6e9vxpwYevMy3zTNPt1qrTPJu53eihWpXdXZvsbMfDVFt0Bp6wEFldwqvdkUikdE+viaidBCxyeIjBBM2j2y5e5qY7GU2B8E=
      github_token:
        secure: XK1vB/wRnY2138Y+okqnptH53NUK4ucnF1iNo3v3u4flp4rkHNurDbz25pSsFU4/0TDqsWZgM9VDxRzF4cvMN1AivvmRu/xlYpgqbR9Tm7uMmD6xssciyL7jmLc04N7Npa8mLmXre3+vQ0dcXARiZ+3GqfuiB0na4qAnU72719wCuE99W/w64JecSM7pyvVSsghFigC5TreBdZrNJO9C36g1brGXh9GwFXEtwIvgb2dGEKZNxPvDOGJKIRrJtY9yCLXp63IPTWWOVNWnKNZvgf1zS+uanBzNztU+z5CpGPs/43w+6dfQeGYv7FskMj8ng7V1TsPGHfn0e7sSDVmcXLY3sEKR53r0NSEUsexmTSmGKW0Eh1t9k0UaXElQTNKBqzwginlloePfkWLLJxngcAQ9jiUwi/FqCdmGfygrb8PdPBPAU5tC4j9lE1eA2/yAkmaOXl7b1OY3NHGhm5iphnTNWYgikH3e4F0pwzx3bBB/1lNUptryrlvZ6Y8yM77izeVKHinSEx1dzI7TX7hbiqv/OgZGzfJWb5CRlTE3hbtEexfuoXCXMj+3s66GPQHq5oGDhoWtRcXW8hVdI6Nj4ANBFQLXfQFIp6aphw7ATvCHTnFA16dlNaz6CxOe/iS8n7x0uufONn0IcDIwc05dH/vMpmG7NZEwHZeFljnchSY=

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar

script:
    - mvn clean test jacoco:report coveralls:report
    - sonar-scanner

